FROM nginx:alpine
COPY . /usr/share/nginx/html/zoombackgroundgenerator

RUN printf '%s\n' \
	'server {' \
	'    listen 80;' \
	'    server_name _;' \
	'    root /usr/share/nginx/html/zoombackgroundgenerator;' \
	'    index index.html;' \
	'' \
	'    location / {' \
	'        try_files $uri $uri/ /index.html;' \
	'    }' \
	'}' > /etc/nginx/conf.d/default.conf