FROM nginx:alpine
COPY . /usr/share/nginx/html/zoombackgroundgenerator

RUN printf '%s\n' \
	'server {' \
	'    listen 80;' \
	'    server_name _;' \
	'    root /usr/share/nginx/html;' \
	'    index index.html;' \
	'' \
	'    location = / {' \
	'        return 302 /zoombackgroundgenerator/;' \
	'    }' \
	'' \
	'    location = /zoombackgroundgenerator {' \
	'        return 301 /zoombackgroundgenerator/;' \
	'    }' \
	'' \
	'    location / {' \
	'        try_files $uri $uri/ /zoombackgroundgenerator/index.html;' \
	'    }' \
	'' \
	'    location /zoombackgroundgenerator/ {' \
	'        alias /usr/share/nginx/html/zoombackgroundgenerator/;' \
	'        try_files $uri $uri/ /zoombackgroundgenerator/index.html;' \
	'    }' \
	'}' > /etc/nginx/conf.d/default.conf